POST http://localhost:3004/login
content-type: application/json

{
  "email": "brondinofabio@gmail.com",
  "password": "4dmin3ur0m1ll1ons"
}

###

POST http://localhost:3004/register
content-type: application/json

{
  "firstname": "Fabio",
  "lastname": "Brondino",
  "email": "brondinofabio@gmail.com",
  "password": "4dmin3ur0m1ll1ons"

}

###

POST http://localhost:3004/login
content-type: application/json

{
  "email": "belledevilleneuve@example.com",
  "password": "Adam"
}

###

POST http://localhost:3004/request-reset-password
content-type: application/json

{
  "email": "brondinofabio@gmail.com"
}

###

POST http://localhost:3004/reset-password
content-type: application/json

{
  "token": "ee9e4600223058dab332cab018a2f9f9eade092c",
  "newPassword": "helloworld"
}

###